# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git'
pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git'

target 'photostream' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photostream

  target 'photostreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'photostreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
